// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kk.Message.proto

/*
Package kk is a generated protocol buffer package.

It is generated from these files:
	kk.Message.proto

It has these top-level messages:
	Message
*/
package kk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	// *
	// 消息ID
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// *
	// 来源消息ID
	Fid int64 `protobuf:"varint,2,opt,name=fid" json:"fid,omitempty"`
	// *
	// 任务类型
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// *
	// 内容类型
	// @type {string}
	ContentType string `protobuf:"bytes,4,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	// *
	// 内容
	// @type {bytes}
	Content []byte `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetFid() int64 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "kk.Message")
}

func init() { proto.RegisterFile("kk.Message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xce, 0xd6, 0xf3,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0xce,
	0x56, 0xaa, 0xe1, 0x62, 0x87, 0x0a, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x30, 0x07, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x70, 0x31, 0xa7, 0x65, 0xa6, 0x48, 0x30, 0x81,
	0x05, 0x40, 0x4c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x30, 0x5b, 0x48, 0x91, 0x8b, 0x27, 0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x24, 0xbe,
	0xa4, 0xb2, 0x20, 0x55, 0x82, 0x05, 0x2c, 0xc7, 0x0d, 0x15, 0x0b, 0xa9, 0x2c, 0x48, 0x15, 0x92,
	0xe0, 0x62, 0x87, 0x72, 0x25, 0x58, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0xdc, 0x24, 0x36, 0xb0,
	0x43, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0xdd, 0x6d, 0xb2, 0x9c, 0x00, 0x00, 0x00,
}
