package app

const ERROR_USER = 0x9000

const ERROR_USER_NOT_FOUND_NAME = ERROR_USER + 1

const ERROR_USER_NAME = ERROR_USER + 2

const ERROR_USER_NOT_FOUND_UID = ERROR_USER + 3

const ERROR_USER_NOT_FOUND = ERROR_USER + 4

const ERROR_USER_NOT_FOUND_PASSWORD = ERROR_USER + 5

const ERROR_USER_PASSWORD = ERROR_USER + 6
